### ISSUE TITLE
JIRA Ticket Regex doesn't support feature branches

### ISSUE THREAD

**Issue by brotheramai** [noplay/vscode-jira-link#1]
If you use bitbucket and jira together it gives you the ability to create branches in your git repository from a ticket in jira.
When you do this you get a branch name of the form:
branchtype/ticketnumber-summary-text-of-jira-issue
For example
feature/ABC-2345-update-dashboard-page

It would be nice if the extension read the regular expression from settings (e.g. jiraLink.ticketRegex)

**Comment by julien-duponchelle** [comment]
Thanks a lot I just published a new release with  this settings configurable
